export const states = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
];

export const stateValues = [
    { key: "andamanAndNicobarIslands", value: "Andaman and Nicobar Islands" },
    { key: "andhraPradesh", value: "Andhra Pradesh" },
    { key: "arunachalPradesh", value: "Arunachal Pradesh" },
    { key: "assam", value: "Assam" },
    { key: "bihar", value: "Bihar" },
    { key: "chandigarh", value: "Chandigarh" },
    { key: "chhattisgarh", value: "Chhattisgarh" },
    { key: "dadraAndNagarHaveliAndDamanAndDiu", value: "Dadra and Nagar Haveli and Daman and Diu" },
    { key: "delhi", value: "Delhi" },
    { key: "goa", value: "Goa" },
    { key: "gujarat", value: "Gujarat" },
    { key: "haryana", value: "Haryana" },
    { key: "himachalPradesh", value: "Himachal Pradesh" },
    { key: "jammuAndKashmir", value: "Jammu and Kashmir" },
    { key: "jharkhand", value: "Jharkhand" },
    { key: "karnataka", value: "Karnataka" },
    { key: "kerala", value: "Kerala" },
    { key: "ladakh", value: "Ladakh" },
    { key: "lakshadweep", value: "Lakshadweep" },
    { key: "madhyaPradesh", value: "Madhya Pradesh" },
    { key: "maharashtra", value: "Maharashtra" },
    { key: "manipur", value: "Manipur" },
    { key: "meghalaya", value: "Meghalaya" },
    { key: "mizoram", value: "Mizoram" },
    { key: "nagaland", value: "Nagaland" },
    { key: "odisha", value: "Odisha" },
    { key: "puducherry", value: "Puducherry" },
    { key: "punjab", value: "Punjab" },
    { key: "rajasthan", value: "Rajasthan" },
    { key: "sikkim", value: "Sikkim" },
    { key: "tamilNadu", value: "Tamil Nadu" },
    { key: "telangana", value: "Telangana" },
    { key: "tripura", value: "Tripura" },
    { key: "uttarPradesh", value: "Uttar Pradesh" },
    { key: "uttarakhand", value: "Uttarakhand" },
    { key: "westBengal", value: "West Bengal" },
];
