const routes = {
    home: "/",
    productsSearch: "/products-search",
    createProduct: "/products/create",
    updateProduct: "/products/update/:id",
    myProducts: "/my-products",
    transportSearch: "/transport-search",
    storageSearch: "/storage-search",
    products: "/products",
    transport: "/transport",
    storage: "/storage",
    profile: "/profile",
    startSelling: "/start-selling",
    login: "/login",
    signupCriteria: "/signup/criteria",
    signupAsUser: "/signup/user",
    signupAsTransport: "/signup/transport-service",
    signupAsStorage: "/signup/storage-service",
    resetPassword: "/reset-password/:id",
    forgotPassword: "/forgot-password",
    productCard: "/product-card",
    changePassword: "/change-password",
    updateUserAsUser: "/updateUser/user",
    updateUserAsTransport: "/updateUser/transport-service",
    updateUserAsStorage: "/updateUser/storage-service",
    productDescription: "/product-description/:id",
    userProfile: "/profile/user",
    storageProfile: "/profile/storage",
    transportProfile: "/profile/transport",
};

export default routes;
